# permissions for end users to edit bucketserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bucketserviceaccount-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: minio-bucket-controller
    app.kubernetes.io/part-of: minio-bucket-controller
    app.kubernetes.io/managed-by: kustomize
  name: bucketserviceaccount-editor-role
rules:
- apiGroups:
  - s3.linka.cloud
  resources:
  - bucketserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.linka.cloud
  resources:
  - bucketserviceaccounts/status
  verbs:
  - get
