apiVersion: v1
kind: Secret
metadata:
  name: minio-bucket-controller-credentials
  namespace: minio-bucket-controller-system
stringData:
  MINIO_ACCESS_KEY: <ACCESS_KEY>
  MINIO_SECRET_KEY: <SECRET_KEY>
  MINIO_ENDPOINT: myminio:9000
  # uncomment if you don't use tls
  # MINIO_INSECURE: "true"
